name: dialect
channels:
- conda-forge
dependencies:
# core
- python=3.10
- numpy
- scikit-learn
- pandas

# audio
- librosa

# jupyter
- jupyterlab

# deps needed by hpelm
- hdf5
- pytables

- pip
- pip:
    - hpelm
